### ISSUE TITLE
Live video support

### ISSUE THREAD

**Issue by gogori2** [Mindinventory/vimeo_video_player#35]
I get error when try to play live video. Does this package supports live streams or I am doing something wrong?

```
E/flutter (29564): Tried calling: map(Closure: (dynamic) => VimeoProgressive)
E/flutter (29564): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
E/flutter (29564): #1      new VimeoFiles.fromJson (package:vimeo_video_player/src/model/vimeo_video_config.dart:24:31)
E/flutter (29564): #2      new VimeoRequest.fromJson (package:vimeo_video_player/src/model/vimeo_video_config.dart:14:38)
E/flutter (29564): #3      new VimeoVideoConfig.fromJson (package:vimeo_video_player/src/model/vimeo_video_config.dart:5:46)
E/flutter (29564): #4      _VimeoVideoPlayerState._getVimeoVideoConfig (package:vimeo_video_player/src/vimeo_player.dart:258:41)
E/flutter (29564): <asynchronous suspension>
E/flutter (29564): #5      _VimeoVideoPlayerState._getVimeoVideoConfigFromUrl (package:vimeo_video_player/src/vimeo_player.dart:246:22)
E/flutter (29564): <asynchronous suspension>
```

**Comment by pratikkansaramind** [comment]
@gogori2 Thank you for expressing your confidence in our team. Unfortunately, we are not supporting live streaming.
